CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Branches" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Branches" PRIMARY KEY ("Id")
);

CREATE TABLE "Logs" (
    "Id" uuid NOT NULL,
    "Request" text NOT NULL,
    "Headers" text NOT NULL,
    "Endpoint" character varying(200) NOT NULL,
    "HttpMethod" character varying(10) NOT NULL,
    "Response" text NOT NULL,
    "Ip" character varying(45) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Logs" PRIMARY KEY ("Id")
);

CREATE TABLE "Patients" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "PasswordHash" text NOT NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id")
);

CREATE TABLE "Doctors" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Description" character varying(500),
    "Image" character varying(200),
    "BranchId" integer,
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Doctors_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Appointments" (
    "Id" uuid NOT NULL,
    "DoctorId" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "Time" timestamp with time zone NOT NULL,
    "Status" character varying(50) NOT NULL,
    "Notes" character varying(500) NOT NULL,
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Ratings" (
    "Id" uuid NOT NULL,
    "DoctorId" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "Score" integer NOT NULL,
    "Comment" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Ratings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Ratings_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Ratings_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TimeSlots" (
    "Id" uuid NOT NULL,
    "DoctorId" uuid NOT NULL,
    "AvailableFrom" interval NOT NULL,
    "AvailableTo" interval NOT NULL,
    "AvailableDay" integer NOT NULL,
    "AppointmentFrequency" integer NOT NULL,
    CONSTRAINT "PK_TimeSlots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TimeSlots_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Appointments_DoctorId" ON "Appointments" ("DoctorId");

CREATE INDEX "IX_Appointments_PatientId" ON "Appointments" ("PatientId");

CREATE INDEX "IX_Doctors_BranchId" ON "Doctors" ("BranchId");

CREATE INDEX "IX_Ratings_DoctorId" ON "Ratings" ("DoctorId");

CREATE INDEX "IX_Ratings_PatientId" ON "Ratings" ("PatientId");

CREATE INDEX "IX_TimeSlots_DoctorId" ON "TimeSlots" ("DoctorId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250307213240_initialCreate', '9.0.2');

COMMIT;

