CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Branches" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Branches" PRIMARY KEY ("Id")
);

CREATE TABLE "Patients" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "PasswordHash" text NOT NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id")
);

CREATE TABLE "Doctors" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Image" character varying(200),
    "BranchId" integer NOT NULL,
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Doctors_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Processes" (
    "Id" uuid NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Duration" integer NOT NULL,
    "DoctorId" uuid NOT NULL,
    CONSTRAINT "PK_Processes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Processes_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Ratings" (
    "Id" uuid NOT NULL,
    "DoctorId" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "Score" integer NOT NULL,
    "Comment" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Ratings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Ratings_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Ratings_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TimeSlots" (
    "Id" uuid NOT NULL,
    "DoctorId" uuid NOT NULL,
    "ProcessId" uuid NOT NULL,
    "AvailableFrom" interval NOT NULL,
    "AvailableTo" interval NOT NULL,
    CONSTRAINT "PK_TimeSlots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TimeSlots_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TimeSlots_Processes_ProcessId" FOREIGN KEY ("ProcessId") REFERENCES "Processes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Appointments" (
    "Id" uuid NOT NULL,
    "DoctorId" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "TimeSlotId" uuid NOT NULL,
    "Status" character varying(50) NOT NULL,
    "Notes" character varying(500) NOT NULL,
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Appointments_TimeSlots_TimeSlotId" FOREIGN KEY ("TimeSlotId") REFERENCES "TimeSlots" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Appointments_DoctorId" ON "Appointments" ("DoctorId");

CREATE INDEX "IX_Appointments_PatientId" ON "Appointments" ("PatientId");

CREATE INDEX "IX_Appointments_TimeSlotId" ON "Appointments" ("TimeSlotId");

CREATE INDEX "IX_Doctors_BranchId" ON "Doctors" ("BranchId");

CREATE INDEX "IX_Processes_DoctorId" ON "Processes" ("DoctorId");

CREATE INDEX "IX_Ratings_DoctorId" ON "Ratings" ("DoctorId");

CREATE INDEX "IX_Ratings_PatientId" ON "Ratings" ("PatientId");

CREATE INDEX "IX_TimeSlots_DoctorId" ON "TimeSlots" ("DoctorId");

CREATE INDEX "IX_TimeSlots_ProcessId" ON "TimeSlots" ("ProcessId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250216121907_initialCreate', '9.0.2');

COMMIT;

